### ISSUE TITLE
关于laplace filter

### ISSUE THREAD

**Issue by Cyanostorm** [wangyusenofficial/NR_3DV#1]
你好，请问哪里有挑选图像质量的laplace filter相关的代码？

**Comment by wangyusenofficial** [comment]
This repository aims to integrate 3DVNet and SurfaceNormalUncertainty into NeuralRoom. So the code here(NR3DV) directly uses the images filtered by 3dvnet as the input of NeuralRoom-3DVNet. The related code maybe you mentioned is attached here:

`import os
import argparse
import shutil
import numpy as np
import cv2

def blur_check(image_path):
    image = cv2.imread(image_path)
    imageVar = cv2.Laplacian(image,cv2.CV_64F).__abs__().sum()
    return imageVar

def get_pose_check(posefile):
    print(posefile)
    flag = 1
    extrinsics_inv = []


    with open(os.path.join(posefile), 'r') as f:
        for line in f:
            extrinsics_inv += [float(value) for value in line.strip().split(' ') if value.strip() != '']
            continue
        pass
    # print(extrinsics_inv[0])
    if np.isinf(extrinsics_inv[0]):
        print('pose file err!')
        print(posefile)
        flag=0
    return flag

# sens_folder = '/home/yswang/Downloads/neus_dataset/raw_data/scene0078_00/s0078_00'
# interval = 5
# output = '/home/yswang/Downloads/neus_dataset/raw_data/scene0078_00/s0078_00/ext'
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--sens_folder', type=str, default='./')
    parser.add_argument('--start_frame', type=int, default=0)
    parser.add_argument('--end_frame', type=int, default=-1)
    parser.add_argument('--start_frame2', type=int, default=-1)
    parser.add_argument('--end_frame2', type=int, default=-1)
    parser.add_argument('--start_frame3', type=int, default=-1)
    parser.add_argument('--end_frame3', type=int, default=-1)
    parser.add_argument('--interval', type=int, default=5)
    parser.add_argument('--output', type=str, default='./output')
    parser.add_argument('--blur_detec', default=False, action='store_true')
    args = parser.parse_args()
    folder = os.listdir(args.sens_folder)
    print(f'find folder: {folder}')

    assert 'color' in folder, 'err: sens folder must contain color images!'

    colorlist = os.listdir(os.path.join(args.sens_folder, 'color'))
    depthlist = os.listdir(os.path.join(args.sens_folder, 'depth'))
    poselist = os.listdir(os.path.join(args.sens_folder, 'pose'))

    assert len(colorlist) == len(depthlist), 'color depth num doesnt match'
    assert len(colorlist) == len(poselist), 'color pose num doesnt match'

    color_file = os.listdir(os.path.join(args.sens_folder, 'color'))
    print(f'find color frames: {color_file.__len__()}')
    if args.end_frame == -1:
        ext_idx = [i for i in range(args.start_frame, color_file.__len__(), args.interval)]
    else:
        ext_idx = [i for i in range(args.start_frame, args.end_frame, args.interval)]
    if args.start_frame2 != -1:
        assert args.end_frame2 != -1, 'must specify a end frame for part2!'
        ext_idx = ext_idx + [i for i in range(args.start_frame2, args.end_frame2, args.interval)]
    if args.start_frame3 != -1:
        assert args.end_frame3 != -1, 'must specify a end frame for part3!'
        ext_idx = ext_idx + [i for i in range(args.start_frame3, args.end_frame3, args.interval)]

    if args.blur_detec:
        pic_all = os.listdir(os.path.join(args.sens_folder, 'color'))
        pic_all = [os.path.join(args.sens_folder, 'color', j) for j in pic_all]
        pose_all = os.listdir(os.path.join(args.sens_folder, 'pose'))
        pose_all = [os.path.join(args.sens_folder, 'pose', j) for j in pose_all]

        arm = args.interval//2.1
        ext_idx_tem = []
        for i in range(ext_idx.__len__()):
            idx = ext_idx[i]
            idxrange = [i for i in range(int(idx-arm),int(idx+arm+1))]
            pics_path = [os.path.join(args.sens_folder, 'color', f'{j}.jpg') for j in idxrange]
            pose_path =  [os.path.join(args.sens_folder, 'pose', f'{j}.txt') for j in idxrange]
            pose_path.sort(key=lambda x:int(x.split('/')[-1].split('.')[0]))
            pics_path.sort(key=lambda x:int(x.split('/')[-1].split('.')[0]))
            check_result = [blur_check(j) if j in pic_all else 0 for j in pics_path]
            pose_check = [get_pose_check(j) if j in pose_all else 0 for j in pose_path]
            id = check_result.index(max(check_result))
            if pose_check[id] != 0:
                ext_idx_tem.append(idxrange[check_result.index(max(check_result))])
            else:
                print('err')
                assert False, ' pose err'
        ext_idx = ext_idx_tem

    print(f'extract frames num: {ext_idx.__len__()}')
    if not os.path.exists(os.path.join(args.output)):
        os.makedirs(os.path.join(args.output))
    if not os.path.exists(os.path.join(args.output,'color')):
        os.makedirs(os.path.join(args.output,'color'))
    with open(os.path.join(args.output,'extract_frame.txt'), 'w') as f:
        for i in range(ext_idx.__len__()):
            f.write(f'{ext_idx[i]}\n')
    [shutil.copyfile(os.path.join(args.sens_folder,'color',f'{ext_idx[idx]}.jpg'),
                     os.path.join(args.output,'color',f'{idx}.jpg')) for idx in range(ext_idx.__len__())]

    if 'depth' in folder:
        depth_file = os.listdir(os.path.join(args.sens_folder,'depth'))
        print(f'find depth frames: {depth_file.__len__()}')
        assert depth_file.__len__() == color_file.__len__(), 'depth num doesnt match color num'
        if not os.path.exists(os.path.join(args.output, 'depth')):
            os.makedirs(os.path.join(args.output, 'depth'))
        [shutil.copyfile(os.path.join(args.sens_folder, 'depth', f'{ext_idx[idx]}.png'),
                         os.path.join(args.output, 'depth', f'{idx}.png')) for idx in range(ext_idx.__len__())]

    if 'pose' in folder:
        pose_file = os.listdir(os.path.join(args.sens_folder, 'pose'))
        print(f'find depth frames: {pose_file.__len__()}')
        assert pose_file.__len__() == color_file.__len__(), 'depth num doesnt match color num'
        if not os.path.exists(os.path.join(args.output, 'pose')):
            os.makedirs(os.path.join(args.output, 'pose'))
        [shutil.copyfile(os.path.join(args.sens_folder, 'pose', f'{ext_idx[idx]}.txt'),
                         os.path.join(args.output, 'pose', f'{idx}.txt')) for idx in range(ext_idx.__len__())]
    # os.makedirs(os.path.join(args.output, 'intrinsic'),exist_ok=True)
    shutil.copytree(os.path.join(args.sens_folder, 'intrinsic'), os.path.join(args.output, 'intrinsic'))`

**Comment by wangyusenofficial** [comment]
This repository aims to integrate 3DVNet and SurfaceNormalUncertainty into NeuralRoom. So the code here(NR3DV) directly uses the images filtered by 3dvnet as the input of NeuralRoom-3DVNet. The related code maybe you mentioned is attached here:
[frame_extraction_scannet.zip](https://github.com/wangyusenofficial/NR_3DV/files/10681281/frame_extraction_scannet.zip)
